SET SERVEROUTPUT ON;

SELECT * FROM TRANSACCION_PAGO;

SELECT * FROM TICKET;

SELECT * FROM SECTOR_RECINTO;

SELECT * FROM CONVENIO_BANCO;

SELECT * FROM RESERVA_TEMPORAL;

SELECT * FROM CLIENTE;

SELECT 
C.NOMBRE || ' '  || C.APELLIDO AS "NOMBRE COMPLETO",
TP.MONTO_BRUTO,
TP.DESCUENTO,
TP.MONTO_FINAL,
TP.ESTADO
FROM 
CLIENTE C 
INNER JOIN RESERVA_TEMPORAL RT
ON C.CLIENTE_ID = RT.CLIENTE_ID
INNER JOIN TRANSACCION_PAGO TP
ON RT.RESERVA_ID = TP.RESERVA_ID
;

--- NOMBRE, MONTO BRUTO, DESCUENTO APLICADO, MONTO FINAL PAGADO, ESTADO DEL PAGO

DECLARE
     TYPE boleta_cliente is RECORD(
        NOMBRE_CLIENTE CLIENTE.NOMBRE%TYPE,
        ESTADO_RESERVA RESERVA_TEMPORAL.ESTADO%TYPE,
        ESTADO_PAGO TRANSACCION_PAGO.ESTADO%TYPE,
        MONTO_BRUTO TRANSACCION_PAGO.MONTO_BRUTO%TYPE,
        DESCUENTO_MONTO TRANSACCION_PAGO.DESCUENTO%TYPE,
        MONTO_FINAL TRANSACCION_PAGO.MONTO_FINAL%TYPE
     );

    v_boleta boleta_cliente;
BEGIN

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    



END;